name: build Re:VIEW PDF
on: [push]
jobs:
  build:
    name: generate PDF
    path: ./
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build PDF
      uses: takahashim/review-pdf-generator-action@master
    - name: upload as Artifacts
      uses: takahashim/review-pdf-generator-action/upload-artifact@master