on: push
name: build pdf
jobs:
  filtersForGitHubActions:
    name: Filters for GitHub Actions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filters for GitHub Actions
      uses: actions/bin/filter@25b7b846d5027eac3315b50a8055ea675e2abd89
      with:
        args: not branch master
    - name: build
      uses: docker://kauplan/review2.5
      with:
        entrypoint: ./scripts/build.sh
    - name: commit
      uses: docker://alpine/git:latest
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      with:
        entrypoint: ./scripts/commit.sh
